// Generated by CoffeeScript 1.4.0
var Findit, GitRepo, GitSupport, Shell, w;

require('colors');

console.log('remove colors');

GitSupport = require('./git_support');

Shell = require('./shell');

Findit = require('findit');

w = require('when');

GitRepo = (function() {

  function GitRepo() {}

  GitRepo.manager = function() {
    return 'none';
  };

  return GitRepo;

})();

module.exports = GitRepo;
